import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  PageContainer: {
    paddingBottom: 100,
    minHeight: '100%',
  },
  ScrollContainer: {
    padding: 14,
    paddingTop: 0,
    display: 'flex',
  },
  PageSubtitle: {
    fontSize: 14,
    marginVertical: 14,
  },
  InvoiceHead: {
    display: 'flex',
    flexDirection: 'column',
    padding: 20,
    flex: 1,
    borderRadius: 5,
    marginTop: 15,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    elevation: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  UserImg: {
    display: 'flex',
    flexDirection: 'column',
    width: 70,
    height: 70,
    resizeMode: 'cover',
    borderRadius: 50,
    borderWidth: 4,
    borderColor: '#8163C7',
    marginBottom: 10,
  },
  UserName: {
    fontSize: 16,
    marginBottom: 5,
    display: 'flex',
    flexDirection: 'row',
    fontWeight: 'bold',
  },
  UserRole: {
    fontSize: 14,
    display: 'flex',
    flexDirection: 'row',
  },
  YourCard: {
    display: 'flex',
    flexDirection: 'row',
    padding: 14,
    // flex: 1,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    elevation: 1,
    position: 'relative',
  },
  YourCardUserImg: {
    width: 35,
    height: 35,
    borderRadius: 20,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  YourCardContent: {
    display: 'flex',
    flexDirection: 'column',
    paddingLeft: 10,
    paddingRight: 5,
  },
  YourCardName: {
    fontSize: 14,
    marginBottom: 3,
    fontWeight: 'bold',
  },
  YourCardNo: {
    fontSize: 13,
    lineHeight: 20,
  },
  DefaultIcon: {
    position: 'absolute',
    top: 22,
    right: 15,
    fontSize: 20,
    color: '#8163C7',
  },
  InvoiceCard: {
    display: 'flex',
    flexDirection: 'column',
    padding: 14,
    marginTop: 15,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    elevation: 1,
    position: 'relative',
  },
  InvoiceCardRow: {
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  InvoiceCardRowTotal: {
    borderTopWidth: 1,
    marginTop: 10,
  },
  InvoiceCardText: {
    display: 'flex',
    flexDirection: 'row',
    fontWeight: 'bold',
  },
  BottomContainer: {
    flex: 1,
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  BottomButton: {
    alignItems: 'center',
    padding: 14,
    borderRadius: 50,
    backgroundColor: '#8163C7',
  },
  BottomButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
})

export default styles
